---
- name: Add user to docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: 
      - docker
    append: true
  register: useradded

- name: Reset connection if user was added to group
  ansible.builtin.include_tasks: reset-connection.yml
  when: useradded.changed

- name: Start the Docker daemon
  become: true
  ansible.builtin.systemd_service:
    state: started
    name: docker

- name: Enable the Docker daemon to start on system boot
  become: true
  ansible.builtin.systemd_service:
    enabled: true
    name: docker

- name: Create mount path for NAS share
  become: true
  ansible.builtin.file:
    path: "{{ docker_setup_mount_path }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: docker
  when: docker_setup_install_nautical is true

- name: Mount backup share from NAS
  become: true
  ansible.posix.mount:
    src: //{{ docker_setup_nas_ip_or_hostname }}/{{ docker_setup_share_name }}
    path: "{{ docker_setup_mount_path }}"
    opts: "rw,vers=3,username={{ docker_setup_share_username }},password={{ docker_setup_share_password }},uid=1000,gid=999"
    fstype: cifs
    state: mounted
  when: docker_setup_install_nautical is true

- name: Install portainer
  ansible.builtin.include_role:
    name: tailscale_container
  vars:
    tailscale_container_tailnet_name: "{{ docker_setup_tailnet_name }}"
    tailscale_container_oauth_client_secret: "{{ docker_setup_tailscale_oauth_client_secret }}"
    tailscale_container_service_name: portainer-{{ ansible_facts['nodename'] }}
    tailscale_container_image: portainer/portainer-ce
    tailscale_container_tag: latest
    tailscale_container_https_container: true
    tailscale_container_serve_port: 9443
    tailscale_container_userspace_networking: "{{ docker_setup_userspace_networking }}"
    tailscale_container_volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/{{ ansible_user }}/portainer-{{ ansible_facts['nodename'] }}/portainer_data:/data
  when: docker_setup_install_portainer is true

- name: Install Nautical-Backup for container volume backups to TrueNAS
  community.general.docker_container:
    name: nautical-{{ ansible_facts['nodename'] }}
    image: minituff/nautical-backup
    state: started
    restart_policy: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/{{ ansible_user }}:/app/source
      - "{{ docker_setup_mount_path }}/{{ ansible_facts['nodename'] }}:/app/destination"
    published_ports:
      - 8096:8096/tcp
    env:
      REQUIRE_LABEL: "true"
      CRON_SCHEDULE: "0 1 * * *"
      TZ: America/New_York
  when: docker_setup_install_nautical is true
...